name: Build and Deploy
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: "liberica"
                    java-version: "21"
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Show Env
                run: |
                    java -version
                    gradle -v
            -   name: Build with Gradle
                run: |
                    chmod a+x ./gradlew
                    ./gradlew clean bootJar
