server:
    port: 8383
spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    application:
        name: boot-server
    profiles:
        active: local
